# file: roles/jboss-eap/init/tasks/main.yml

- name: create group
  group: name={{ eap_group }}

- name: create user
  user: name={{ eap_user }} group={{ eap_group }}

- name: set EAP_HOME in /etc/profile.d/jboss-eap.sh
  template: src=jboss-eap.sh dest=/etc/profile.d mode=u=rw,g=r,o=r

- name: copy standalone.xml
  template: src=standalone.xml dest={{ eap_home_dir }}/standalone/configuration

- name: create PostgreSQL JDBC Driver module directory
  file: path={{ eap_pgsql_module_dir }} owner={{ eap_user }} group={{ eap_group }} state=directory

- name: copy PostgreSQL JDBC Driver jar
  copy: src={{ eap_pgsql_jdbc_jar }} dest={{ eap_pgsql_module_dir }} owner={{ eap_user }} group={{ eap_group }}

- name: create PostgreSQL JDBC Driver module xml
  template: src=module.xml dest={{ eap_pgsql_module_dir }}

- name: create JBoss EAP service configuration file
  template: src=jboss-eap.conf dest=/etc/default

- name: create JBoss EAP service startup script
  template: src=jboss-eap-rhel.sh dest=/etc/init.d/jboss-eap mode=u+rwx,g=rx,o=rx
