# file: roles/jenkins/install/tasks/main.yml

- name: stop Jenkins, if running
  service: name={{ package_name }} state=stopped
  ignore_errors: true

- name: import Jenkins GPG Key
  rpm_key: key={{ key_url }}

- name: install Jenkins Yum Repository
  get_url: url={{ repo_url }} dest=/etc/yum.repos.d/jenkins.repo

- name: install Jenkins
  yum: name={{ package_name }}

- name: set JENKINS_PORT in /etc/sysconfig/jenkins
  replace: dest=/etc/sysconfig/jenkins regexp='^JENKINS_PORT="8080"' replace='JENKINS_PORT="{{ jenkins_port }}"' backup=yes

- name: set JENKINS_USER to root in /etc/sysconfig/jenkins
  replace: dest=/etc/sysconfig/jenkins regexp='^JENKINS_USER="jenkins"' replace='JENKINS_USER="{{ jenkins_user }}"' backup=no

- name: set JENKINS_AJP_PORT to -1 in /etc/sysconfig/jenkins
  replace: dest=/etc/sysconfig/jenkins regexp='^JENKINS_AJP_PORT="8009"' replace='JENKINS_AJP_PORT="-1"' backup=yes

- name: copy jenkins data dir archive fragments
  copy: src={{ item }} dest=/tmp
  with_items:
    - "{{ jenkins_data_archive }}._aa"
    - "{{ jenkins_data_archive }}._ab"
    - "{{ jenkins_data_archive }}._ac"
    - "{{ jenkins_data_archive }}._ad"
    - "{{ jenkins_data_archive }}._ae"
    - "{{ jenkins_data_archive }}._af"
    - "{{ jenkins_data_archive }}._ag"
    - "{{ jenkins_data_archive }}._ah"
    - "{{ jenkins_data_archive }}._ai"
    - "{{ jenkins_data_archive }}._aj"
    - "{{ jenkins_data_archive }}._ak"
    - "{{ jenkins_data_archive }}._al"
    - "{{ jenkins_data_archive }}._am"
    - "{{ jenkins_data_archive }}._an"
    - "{{ jenkins_data_archive }}._ao"
    - "{{ jenkins_data_archive }}._ap"
    - "{{ jenkins_data_archive }}._aq"
    - "{{ jenkins_data_archive }}._ar"
    - "{{ jenkins_data_archive }}._as"
    - "{{ jenkins_data_archive }}._at"
    - "{{ jenkins_data_archive }}._au"

- name: join fragments
  command: sh -c "cat /tmp/{{ jenkins_data_archive_fragments }} > /tmp/{{ jenkins_data_archive }}"

- name: delete /var/lib/jenkins
  file: path=/var/lib/jenkins state=absent

- name: unarchive jenkins data dir
  unarchive: src="/tmp/{{ jenkins_data_archive }}" dest=/var/lib copy=no
  environment:
    LANG: "C"
    LC_ALL: "C"
    LC_MESSAGES: "C"

- name: start Jenkins
  service: name={{ package_name }} state=started
